name: Deploy Angular App

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build -- --configuration=production

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ awellamgh.com }}
          username: ${{ root }}
          password: ${{ Yaw2002Afreh# }}
          source: "dist/awellam-dash-board/browser*"
          target: "/var/www/AwellamDashboard/dist/awellam-dash-board/browser"
